server:
  port: 7125

myqueue: notice-queue
mytopic: notice-topic

spring:
  application:
    name: user
  zipkin:
    base-url: http://127.0.0.1:9411/
    discovery-client-enabled: true
  jms:
    pub-sub-domain: false
  jpa:
    show-sql: true
  mvc:
    servlet:
      load-on-startup: 1
  activemq:
    broker-url: tcp://127.0.0.1:61616
    in-memory: false
    user: admin
    password: admin
  redis:
    host: 8.136.133.5
    port: 6379
    jedis:
      pool:
        max-active: 100
        min-idle: 5
        max-idle: 10
        max-wait: 1000
    timeout: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.136.133.5:3306/common_diary
    username: root
    password: Guzx.@970712
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 100
      time-between-eviction-runs-millis: 200000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat,slf4j,wall
      url: jdbc:mysql://8.136.133.5:3306/common_diary?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
      username: root
      password: Guzx.@970712
      keep-alive: true
      max-pool-prepared-statement-per-connection-size: 20


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:7121/eureka
    fetch-registry: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pers.guzx.user.entity

logging:
  file:
    name: user-all.log
  level:
    pers:
      guzx:
        user:
          mapper: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

feign:
  httpclient:
    enabled: true

management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true