server:
  port: 7122

ip: 8.136.133.5

spring:
  application:
    name: gateway
  zipkin:
    base-url: http://${ip}:9411/
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

#eureka:
#  client:
#    fetch-registry: true
#    service-url:
#      defaultZone: http://admin:admin@${spring.cloud.client.ip-address}:7121/eureka
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always