server:
  port: 7123

ip: 127.0.0.1

spring:
  zipkin:
    discovery-client-enabled: true
    base-url: http://${ip}:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: admin-monitor
  security:
    user:
      name: "admin"
      password: "admin"
  mail:
    host: smtp.163.com
    username: qq2544697696@163.com
    password: WUVLUVRGONACSUUX
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enabled: true
          starttls:
            enabled: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    default-encoding: UTF-8
    port: 465
  boot:
    admin:
      notify:
        mail:
          to: hnguzx@qq.com
          from: qq2544697696@163.com

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@${spring.cloud.client.ip-address}:7121/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health

management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
