server:
  port: 7126

spring:
  application:
    name: demo
  zipkin:
    base-url: http://127.0.0.1:9411/
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://8.136.133.5:3306/demo
    url: jdbc:mysql://127.0.0.1:3306/common_diary
    username: root
#    password: Guzx.@970712
    password: 970712
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat,log4j2,wall
#      url: jdbc:mysql://8.136.133.5:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
      url: jdbc:mysql://127.0.0.1:3306/common_diary?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
      username: root
#      password: Guzx.@970712
      password: 970712


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://admin:admin@${spring.cloud.client.ip-address}:7121/eureka
    fetch-registry: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pers.guzx.demo.entity

logging:
  file:
    name: demo-all.log
  level:
    pers:
      guzx:
        demo:
          mapper: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

