server:
  port: 7123

spring:
  application:
    name: demo
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://8.136.133.5:3306/demo
    username: root
    password: Guzx.@970712
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
      validation-query: select 1
      pool-prepared-statements: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
      filters: stat

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:7121/eureka
    fetch-registry: true
