server:
  port: 7123

spring:
  application:
    name: demo
  zipkin:
    base-url: http://127.0.0.1:9411/
    discovery-client-enabled: true
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.136.133.5:3306/demo
    username: root
    password: Guzx.@970712
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat,log4j2,wall
      url: jdbc:mysql://8.136.133.5:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
      username: root
      password: Guzx.@970712
#  sql:
#    init:
#      encoding: utf-8
#      separator: ;
#      mode: always
#      schema-locations: classpath:schame.sql
#      data-locations: classpath:data.sql


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:7121/eureka
    fetch-registry: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pers.guzx.demo.entity

logging:
  file:
    name: demo-all.log
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
  level:
    pers:
      guzx:
        demo:
          mapper: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true

