server:
  port: 7121

ip: 127.0.0.1

spring:
  application:
    name: registry
  zipkin:
    base-url: http://${ip}:9411/
    discovery-client-enabled: true
    sender:
      type: web # 后面改为activeMQ
  sleuth:
    sampler:
      probability: 1.0
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: F:\logs\eureka\eureka-server\eureka-server-all.log