server:
  port: 7121

spring:
  application:
    name: registry
  zipkin:
    base-url: http://127.0.0.1:9411/
    discovery-client-enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always